image:
  repository: ghcr.io/psyyak/order-service
  tag: "71c42e4"
env:
  - name: SECRET_KEY
    value: "dev-secret-order"
  - name: APP_ENV
    value: "dev"

service:
  type: LoadBalancer
  port: 80
  nodePort: 30012