apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app.kubernetes.io/name: {{ include "user-service.name" . }} }
  template:
    metadata:
      labels: { app.kubernetes.io/name: {{ include "user-service.name" . }} }
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
          {{- end }}
