apiVersion: v1
kind: Service
metadata:
  name: {{ include "order-service.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector: { app.kubernetes.io/name: {{ include "order-service.name" . }} }
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
